"""initial clean schema

Revision ID: 37668cdf645b
Revises: 
Create Date: 2026-05-02 15:53:43.926316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '37668cdf645b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_node_id', sa.Uuid(), nullable=False),
    sa.Column('to_node_id', sa.Uuid(), nullable=False),
    sa.Column('transport_types', sa.JSON(), nullable=False),
    sa.Column('base_travel_time_min', sa.Integer(), nullable=False),
    sa.Column('base_travel_time_max', sa.Integer(), nullable=False),
    sa.Column('base_cost_min', sa.Float(), nullable=False),
    sa.Column('base_cost_max', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['from_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_from_node_id'), 'edges', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_edges_to_node_id'), 'edges', ['to_node_id'], unique=False)
    op.create_table('saved_places',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('start_node_id', sa.Uuid(), nullable=False),
    sa.Column('end_node_id', sa.Uuid(), nullable=False),
    sa.Column('searched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['end_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['start_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edge_status',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('edge_id', sa.Uuid(), nullable=False),
    sa.Column('transport_type', sa.String(), nullable=False),
    sa.Column('queue_level', sa.Enum('low', 'medium', 'high', name='queue_level_enum'), nullable=False),
    sa.Column('vehicle_availability', sa.Enum('available', 'limited', 'unavailable', name='vehicle_availability_enum'), nullable=False),
    sa.Column('estimated_wait_time', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('recent_reports_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['edges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edge_id', 'transport_type', name='uq_edge_status_edge_transport')
    )
    op.create_index(op.f('ix_edge_status_edge_id'), 'edge_status', ['edge_id'], unique=False)
    op.create_index(op.f('ix_edge_status_transport_type'), 'edge_status', ['transport_type'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('edge_id', sa.Uuid(), nullable=False),
    sa.Column('transport_types', sa.JSON(), nullable=False),
    sa.Column('queue_level', sa.Enum('low', 'medium', 'high', name='queuelevel'), nullable=False),
    sa.Column('vehicle_availability', sa.Enum('available', 'limited', 'unavailable', name='vehicleavailability'), nullable=False),
    sa.Column('estimated_wait_time', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('additional_message', sa.String(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('location_distance_meters', sa.Float(), nullable=True),
    sa.Column('location_score', sa.Float(), nullable=False),
    sa.Column('device_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['edges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_edge_id'), 'reports', ['edge_id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_edge_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_edge_status_transport_type'), table_name='edge_status')
    op.drop_index(op.f('ix_edge_status_edge_id'), table_name='edge_status')
    op.drop_table('edge_status')
    op.drop_table('search_history')
    op.drop_table('saved_places')
    op.drop_index(op.f('ix_edges_to_node_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_from_node_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('nodes')
    # ### end Alembic commands ###
